services:
  - type: static_site
    name: smart-school-client
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
